export default function About() {
    return (
        <>
            <h1>About</h1>
            <p>Flatfish was built with <a href="https://www.npmjs.com/package/react-chessboard">react-chessboard</a> and <a href="https://www.npmjs.com/package/chess.js?activeTab=readme">chess.js</a>.</p>
            <p>The Flatfish icon was generated by ChatGPT 
                -- I asked it to generate an SVG of a fish, and it ... did? 
                Flatfish may not be seaworthy, but I do think he's pretty cute. 
            </p>

            {/* <h2>Todos</h2> 
             <p>TODO: Flesh out main page</p>
            <p>TODO: Play RME</p>
            <p>TODO: Delete items from history</p>
            <p>TODO: Deploy</p>
            <p>TODO: About page</p>
            <p>TODO: Display bug -- board gets bigger when you make an invalid move</p>
            <p>TODO: RME bug -- if move is illegal, a random move will be played instead</p>
            <p>STRETCH: Fix CSS with gridbox</p>
            <p>STRETCH: CheckmateAvoider -- he attac, he protec, he try to avoid check</p> */}
        </>
    )
}